* configure: Add a check, in the case that we cannot make an executable, whether this is due to being required to use C99. For instance, the Solaris environment requires compilation using the C99 dialect if _XOPEN_SOURCE is set to 600 or higher.
* debug.c: When compiling as C99, we have to obey the special
C99 conventions for instantiating inline functions.

* hash.c: Likewise.

* lib.c: Likewise.

* parser.y: Likewise.

* unwind.c: Likewise.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -704,13 +704,21 @@ int main(void)
 !
 
 if ! conftest ; then
-  printf "failed\n\n"
-  printf "Errors from compilation: \n\n"
-  cat conftest.err
-  exit 1
+  printf "failed\n"
+  printf "Checking whether the failure is due to a requirement to use C99 ... "
+  if conftest EXTRA_FLAGS=-std=c99 ; then
+    printf "yes\n"
+    lang_flags="$(echo "$lang_flags" | sed -e 's/-ansi/-std=c99/')"
+  else
+    printf "no\n\n"
+    conftest && true
+    printf "Errors from compilation: \n\n"
+    cat conftest.err
+    exit 1
+  fi
+else
+  printf "okay\n"
 fi
-
-printf "okay\n"
 
 printf "Checking whether executables have that idiotic .exe suffix ... "
 
